import type { MwhModule } from "../../types.js";

const CONTENT = `# MWH Module: OTP Code Verifier

## Purpose

Use this module as a reusable reference for one-time verification code flows: email verification, SMS login, step-up authentication, device binding, and transactional confirmation.

The module focuses on code lifecycle semantics. Delivery belongs in email, SMS, push, or voice adapters; this package only generates/verifies codes, stores hashes, enforces TTL and attempts, controls resend cooldowns, and consumes valid codes once.

## When To Use

- Need one-time numeric codes for login, signup, MFA, or sensitive operations.
- Need provider-independent verification logic before wiring SMS/email delivery.
- Need hashed code storage, TTL, brute-force attempt limits, and one-time consume.
- Need deterministic tests for resend cooldown and expiry behavior.

## When Not To Use

- Do not store raw OTP codes in durable storage.
- Do not use long-lived codes for account login.
- Do not expose whether a phone number or email exists.
- Do not rely on an in-memory store for production MFA.

## Implementation Variants

- Memory store for tests and local prototypes.
- Redis store using TTL keys and Lua/transactions for atomic attempts and consume.
- SQL table keyed by id/subject/purpose with code_hash, status, attempts, expires_at, and resend_after.
- TOTP adapter using RFC 6238 time-window verification when the code is generated by an authenticator app.
- Delivery adapters that call existing email/SMS/push modules and never log raw codes.

## Recommended Architecture

- core.ts: numeric code generation, salted hash, timing-safe comparison, lifecycle classification, resend cooldown check, consume/revoke transitions, and clone helpers.
- memory-store.ts: stateful issue, verify, consume, canResend, revoke, pruneExpired, get, and list behavior.
- adapters/redis.ts: atomic verify attempt increment, lockout, consume, TTL, and resend cooldown.
- adapters/sql.ts: durable status transitions and audit-friendly verification records.
- integrations/delivery.ts: provider-specific delivery built on email/sms/push adapters.

## Public API Sketch

\`\`\`ts
const store = new MemoryOtpCodeStore();
const { code } = store.issue({
  id: "otp-1",
  subjectId: "user-1",
  channel: "sms",
  purpose: "login",
  ttlMs: 300_000,
});

await sms.send({ to: phone, body: \`Your code is \${code}\` });
const result = store.consume("otp-1", userInputCode);
if (result.status !== "valid") throw new Error("invalid code");
\`\`\`

## Integration Rules

1. Store only hashes of OTP codes.
2. Keep numeric OTP TTL short, typically 3 to 10 minutes.
3. Limit attempts and lock the code after repeated failures.
4. Consume a valid code exactly once.
5. Enforce resend cooldown per subject, purpose, and channel.
6. Return generic public responses and avoid account enumeration.
7. Never log raw codes.

## Failure Modes

- Raw code persistence exposes active login or MFA codes.
- Missing attempt limits enables brute force.
- Missing atomic consume allows replay during concurrent submissions.
- Resend without cooldown creates delivery abuse and cost spikes.
- Provider delivery failures are mixed with verification state.

## Verification Checklist

- Stateless tests cover code generation, salted hashing, timing-safe verification, record creation, expiry classification, resend cooldown, mismatch attempt tracking, lockout, consume, revoke, and clone safety.
- Stateful tests cover issue, duplicate rejection, verify, failed-attempt persistence, lockout, consume once, resend cooldown, revoke, pruneExpired, subject filtering, and clone-safe records.
- Redis/SQL adapters should test atomic verify/consume and concurrent failed-attempt updates.
- Delivery integration tests should ensure raw codes are not logged and provider failures do not mark codes consumed.

## Source References

- One-time password login and MFA patterns.
- OWASP authentication and MFA guidance.
- Redis TTL one-time token storage.
- SQL status-transition tables for auditable verification flows.
`;

export const OTP_CODE_VERIFIER_MODULE: MwhModule = {
  id: "otp-code-verifier",
  title: "OTP Code Verifier",
  summary:
    "Reusable auth-security reference for one-time verification codes, hashed storage, TTL, resend cooldown, attempt lockout, consume, and provider-independent delivery adapters.",
  version: "0.1.0",
  tags: ["auth-security", "otp", "mfa", "verification-code", "middleware"],
  source: { kind: "builtin", label: "Carbon Code built-in" },
  content: CONTENT,
};
